### ISSUE TITLE
Include the full pathname in the RSS entries.

### ISSUE THREAD

**Issue by dougo** [iftechfoundation/ifarchive-ifmap-py#33]
It might be nice to include the full pathname of the added entry in the new-additions RSS feed. Currently the title is just the bare filename, and the body is the index description (if any). We could put the path in the title, or maybe as the first line of the description.

**Comment by erkyrath** [comment]
How's this? The RSS stanzas now look like

```
    <item>
    <title>The Lottery Ticket.zip</title>
    <link>https://ifarchive.org/if-archive/games/competition2022/Games/The%20Lottery%20Ticket.zip</link>
    <guid>if-archive/games/competition2022/Games/The%20Lottery%20Ticket.zip::1723326921</guid>
    <pubDate>Sat, 10 Aug 2024 21:55:21 +0000</pubDate>
    <description>
    [at: if-archive/games/competition2022/Games/The%20Lottery%20Ticket.zip]
    </description>
    </item>
```

(With the listed description before the `[at:...]` line, if present.)
