### ISSUE TITLE
Log rotation on rsync log file

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifarchive-ifmap-py#37]
(Not actually an issue with this repo, but I have to file it somewhere.)

rsync.log is currently at 10MB and rising.

**Comment by pmazaitis** [comment]
I'm happy to take the baton on this (plan: set it up similar to what we have/had for the ftpd logs).

**Comment by erkyrath** [comment]
Feel free!

**Comment by pmazaitis** [comment]
Progress!

 - Log rotation conf script created
 - Tested that the script would restart service to free file handle
 - Added notes to the rsync documentation file

Minor mea culpa: I surprised myself testing the restart functionality, so I may have bounced an active connection (grn).

Let's wait a week and see what happens.

**Comment by pmazaitis** [comment]
Log rotation should now be active on the rysncd.log file. This has been tested by hand; I will check the logs tomorrow to make sure that the automated run doesn't have any issues. Notes are in the docs file.

**Comment by pmazaitis** [comment]
automatic log rotation for the rsyncd log appears to be working.

**Comment by pmazaitis** [comment]
Log rotation continues to work without complanit; think we're good
