### ISSUE TITLE
Date lists with descriptions?

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifarchive-ifmap-py#38]
> The new-arrivals indexes ([like this one](https://ifarchive.org/indexes/date_1.html)) only list the pathname, and not its description. If you're looking at these, it's natural to want to see the new files' descriptions and metadata. (I know the RSS feed is better.)

My comment:

Descriptions in the "past week" and "past month" file seem reasonable. Maybe that's optional though? Separate links for "list of files" and "list of files with descriptions"?

**Comment by dfabulich** [comment]
IMO all of the `date_#.html` files would benefit from descriptions, even "all time."

It's hard for me to imagine a kind of person who wants to see a list of files but doesn't need/care about the descriptions.

**Comment by erkyrath** [comment]
There's always somebody who you didn't imagine.

**Comment by erkyrath** [comment]
I suspect this will be a noticeable slowdown to index generation. I'll have to measure.

**Comment by erkyrath** [comment]
Done. Adds about a second to the rebuild time, which is not a big deal.

New verbose lists are at https://ifarchive.org/indexes/datev_1.html , etc. The old lists are still at https://ifarchive.org/indexes/date_1.html ; these have not changed except that the titles say "(names only)". The sidebar menu lists both.

For what it's worth, the verbose list-of-all-files page is about 60% larger than the brief
version. (8.6Mb rather than 5.3 Mb.)
