### ISSUE TITLE
Can <wbr> tags be used in the index? 

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifarchive-ifmap-py#9]
Could `<wbr>` tags be added after slashes in the indexes, to avoid breaking words across lines? It would also avoid the awkward "if-" being on a line by itself.

![Mobile screenshot showing suboptimal formatting](https://user-images.githubusercontent.com/59074/54691252-a2b88c00-4b6e-11e9-8d46-464eada75fd1.JPG)

**Comment by erkyrath** [comment]
Done. I added `<wbr>` after slash in the header line and the Subdirectories list.

**Comment by erkyrath** [comment]
And also the "by date" and "list of all directories" pages.
